# permissions for end users to edit vmalerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmalert-editor-role
rules:
- apiGroups:
  - victoriametrics.victoriametrics.com
  resources:
  - vmalerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - victoriametrics.victoriametrics.com
  resources:
  - vmalerts/status
  verbs:
  - get
