# permissions for end users to view vmalerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmalert-viewer-role
rules:
- apiGroups:
  - victoriametrics.victoriametrics.com
  resources:
  - vmalerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - victoriametrics.victoriametrics.com
  resources:
  - vmalerts/status
  verbs:
  - get
