# permissions for end users to view vmpodscrapes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmpodscrape-viewer-role
rules:
- apiGroups:
  - victoriametrics.victoriametrics.com
  resources:
  - vmpodscrapes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - victoriametrics.victoriametrics.com
  resources:
  - vmpodscrapes/status
  verbs:
  - get
