# permissions for end users to edit vmsingles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmsingle-editor-role
rules:
- apiGroups:
  - victoriametrics.victoriametrics.com
  resources:
  - vmsingles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - victoriametrics.victoriametrics.com
  resources:
  - vmsingles/status
  verbs:
  - get
