apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: vm-operator
  name: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-operator
  namespace: default
  labels:
    control-plane: vm-operator
spec:
  selector:
    matchLabels:
      control-plane: vm-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: vm-operator
    spec:
      containers:
      - name: vm-operator
        image: quay.io/f41gh7/vm-operator:latest
        imagePullPolicy: Always
        command:
        - vm-operator
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "vm-operator"
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
