apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v0.19.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: VMAgent represents a Victoria-Metrics agent application
      displayName: VMAgent App
      kind: VMAgent
      name: vmagents.operator.victoriametrics.com
      resources:
      - kind: Deployment
        name: ""
        version: apps
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      specDescriptors:
      - description: 'Labels Map of string keys and values that can be used to organize
          and categorize (scope and select) objects. May match selectors of replication
          controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        displayName: PodLabels
        path: podMetadata.labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: ReplicaCount is the expected size of the VMAgent cluster. The
          controller will eventually make the size of the running cluster equal to
          the expected size. NOTE enable VMSingle deduplication for replica usage
        displayName: Pod Count
        path: replicaCount
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: Resources container resource request and limits, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          if not specified - default setting will be used
        displayName: Resources
        path: resources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      version: v1beta1
    - description: VMAlert represents a Victoria-Metrics alert application
      displayName: VMAlert App
      kind: VMAlert
      name: vmalerts.operator.victoriametrics.com
      resources:
      - kind: Deployment
        name: ""
        version: v1
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      specDescriptors:
      - description: 'Labels Map of string keys and values that can be used to organize
          and categorize (scope and select) objects. May match selectors of replication
          controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        displayName: PodLabels
        path: podMetadata.labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: ReplicaCount is the expected size of the VMAlert cluster. The
          controller will eventually make the size of the running cluster equal to
          the expected size.
        displayName: Pod Count
        path: replicaCount
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: Resources container resource request and limits, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        displayName: Resources
        path: resources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      version: v1beta1
    - description: VMAlertmanager represents Victoria-Metrics deployment for Alertmanager.
      displayName: VMAlertmanager App
      kind: VMAlertmanager
      name: vmalertmanagers.operator.victoriametrics.com
      resources:
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      - kind: StatefulSet
        name: ""
        version: apps
      specDescriptors:
      - description: 'Labels Map of string keys and values that can be used to organize
          and categorize (scope and select) objects. May match selectors of replication
          controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        displayName: PodLabels
        path: podMetadata.labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: ReplicaCount Size is the expected size of the alertmanager cluster.
          The controller will eventually make the size of the running cluster equal
          to the expected
        displayName: Pod Count
        path: replicaCount
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: Resources container resource request and limits, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        displayName: Resources
        path: resources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      - description: 'Labels Map of string keys and values that can be used to organize
          and categorize (scope and select) objects. May match selectors of replication
          controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        displayName: PodLabels
        path: storage.volumeClaimTemplate.labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      version: v1beta1
    - description: VMPodScrape is the Schema for the podscrapes API it generates vmagent's
        config for scraping pod targets based on selectors
      displayName: VMPodScrape
      kind: VMPodScrape
      name: vmpodscrapes.operator.victoriametrics.com
      specDescriptors:
      - description: Selector to select Pod objects.
        displayName: Pod selector
        path: selector
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:selector:'
      version: v1beta1
    - description: VMRule defines rule records for vmalert application
      displayName: VMRule
      kind: VMRule
      name: vmrules.operator.victoriametrics.com
      version: v1beta1
    - description: VMServiceScrape is the Schema for the servicescrapes API it generates
        scrape configuration for vmagent based on selectors result config will scrape
        service endpoints
      displayName: VMServiceScrape
      kind: VMServiceScrape
      name: vmservicescrapes.operator.victoriametrics.com
      specDescriptors:
      - description: Selector to select Endpoints objects.
        displayName: Service selector
        path: selector
        x-descriptors:
        - 'urn:alm:descriptor:com.tectonic.ui:selector:'
      version: v1beta1
    - description: VMSingle represents a Victoria-Metrics single database
      displayName: VMSingle App
      kind: VMSingle
      name: vmsingles.operator.victoriametrics.com
      resources:
      - kind: Deployment
        name: ""
        version: apps
      - kind: Secret
        name: ""
        version: v1
      - kind: Service
        name: ""
        version: v1
      specDescriptors:
      - description: 'Labels Map of string keys and values that can be used to organize
          and categorize (scope and select) objects. May match selectors of replication
          controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        displayName: PodLabels
        path: podMetadata.labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: ReplicaCount is the expected size of the VMSingle it can be 0
          or 1 if you need more - use vm cluster
        displayName: Pod Count
        path: replicaCount
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: Resources container resource request and limits, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
          if not defined default resources from operator config will be used
        displayName: Resources
        path: resources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      version: v1beta1
    - description: VMCluster represents a Victoria-Metrics database cluster
      displayName: VMCluster App
      kind: VMCluster
      name: vmclusters.operator.victoriametrics.com
      resources:
      - kind: Deployment
        name: ""
        version: apps
      - kind: Service
        name: ""
        version: v1
      - kind: Statefulset
        name: ""
        version: apps
      specDescriptors:
      - description: 'Labels Map of string keys and values that can be used to organize
          and categorize (scope and select) objects. May match selectors of replication
          controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        displayName: PodLabels
        path: vminsert.podMetadata.labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: ReplicaCount is the expected size of the VMSelect cluster. The
          controller will eventually make the size of the running cluster equal to
          the expected size.
        displayName: Pod Count
        path: vminsert.replicaCount
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: Resources container resource request and limits, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        displayName: Resources
        path: vminsert.resources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      - description: 'Labels Map of string keys and values that can be used to organize
          and categorize (scope and select) objects. May match selectors of replication
          controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        displayName: PodLabels
        path: vmselect.persistentVolume.volumeClaimTemplate.labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: 'Labels Map of string keys and values that can be used to organize
          and categorize (scope and select) objects. May match selectors of replication
          controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        displayName: PodLabels
        path: vmselect.podMetadata.labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: ReplicaCount is the expected size of the VMSelect cluster. The
          controller will eventually make the size of the running cluster equal to
          the expected size.
        displayName: Pod Count
        path: vmselect.replicaCount
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: Resources container resource request and limits, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        displayName: Resources
        path: vmselect.resources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      - description: 'Labels Map of string keys and values that can be used to organize
          and categorize (scope and select) objects. May match selectors of replication
          controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        displayName: PodLabels
        path: vmstorage.podMetadata.labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      - description: ReplicaCount is the expected size of the VMSelect cluster. The
          controller will eventually make the size of the running cluster equal to
          the expected size.
        displayName: Pod Count
        path: vmstorage.replicaCount
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:podCount
      - description: Resources container resource request and limits, https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
        displayName: Resources
        path: vmstorage.resources
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:resourceRequirements
      - description: 'Labels Map of string keys and values that can be used to organize
          and categorize (scope and select) objects. May match selectors of replication
          controllers and services. More info: http://kubernetes.io/docs/user-guide/labels'
        displayName: PodLabels
        path: vmstorage.storage.volumeClaimTemplate.labels
        x-descriptors:
        - urn:alm:descriptor:com.tectonic.ui:label
      version: v1beta1
  description: VictoriaMetrics operator
  displayName: victoria-metrics-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - monitoring
  - victoria-metrics
  - prometheus
  links:
  - name: Operator
    url: https://operator.domain
  maintainers:
  - email: info@victoriametrics.com
    name: victoria-metrics
  maturity: alpha
  provider:
    name: vm-operator
    url: https://github.com/VictoriaMetrics/VictoriaMetrics
  version: 0.0.0
