apiVersion: apps/v1
kind: Deployment
metadata:
  name: vm-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vm-operator
  template:
    metadata:
      labels:
        name: vm-operator
    spec:
      serviceAccountName: vm-operator
      containers:
        - name: vm-operator
          # Replace this with the built image name
          image: quay.io/f41gh7/vm-operator:latest
          command:
          - vm-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "vm-operator"
