name: Build and Test

# This workflow will run on master branch and on any pull requests targeting master
on:
  push:
    branches:
      - '*'
    tags: []
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      - name: Setup Go
        uses: actions/setup-go@master
        with:
          go-version: 1.13
        id: go
      - name: Dependencies
        env:
          GO111MODULE: on
        run: |
          go get  golang.org/x/lint/golint
          go get github.com/kisielk/errcheck
          go get  github.com/golangci/golangci-lint/cmd/golangci-lint@v1.27.0
      - name: Code checkout
        uses: actions/checkout@master
      - name: build binary
        env:
          GO111MODULE: on
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin # temporary fix. See https://github.com/actions/setup-go/issues/14
          make lint
          make test
          make build-app

      - name: build docker
        uses: docker/build-push-action@v1
        with:
          username: ${{secrets.REPO_USER}}
          password: ${{secrets.REPO_KEY}}
          registry: "quay.io"
          repository: f41gh7/vm-operator
          tag_with_ref: true
          dockerfile: cmd/manager/Dockerfile

# TODO fix it, for some reason it fails with timeout
#      - name: Setup Minikube for e2e
#        uses: manusa/actions-setup-minikube@v1.0.2
#        with:
#            minikube version: 'v1.5.2'
#            kubernetes version: 'v1.16.0'
#            github token: ${{ secrets.GITHUB_TOKEN }}
#      - name: exec e2e tests
#        env:
#          GO111MODULE: on
#          E2E_IMAGE: ${{ env.GITHUB_REF_SLUG }}
#          SDK_VERSION: "0.17.0"
#        run: |
#          export PATH=$PATH:$(go env GOPATH)/bin
#          export PATH=$PATH:`pwd`
#          kubectl get nodes
#          curl -L -o operator-sdk "https://github.com/operator-framework/operator-sdk/releases/download/v0.17.0/operator-sdk-v0.17.0-x86_64-linux-gnu"
#          chmod +x operator-sdk
#          make e2e
